### ISSUE TITLE
@ImmutableContext() doesn't work with Receiver() properly

### ISSUE THREAD

**Issue by luthor77** [ngxs-labs/immer-adapter#225]
Before the change from produce operator to ImmutableContext decorator, the Receiver decorator from Emitter plugin had the implementation with immer-adapter documented here, now it doesn't.

It works with the new decorator, but it gives this error, preventing from compiling in aot:
![erro-immer-emmiter](https://user-images.githubusercontent.com/31356395/59200500-c9370380-8b6e-11e9-8cd3-08eae23ec7e2.png)

The immer-adapter won't give support anymore to Emmiter plugin?

**Comment by splincode** [comment]
Please add stackblitz example for reproduce

**Comment by splincode** [comment]
Because immer-adapter integrated with emitter

https://github.com/ngxs-labs/immer-adapter/blob/master/src/tests/helpers/todo.helper.ts

**Comment by luthor77** [comment]
You can see

**Comment by luthor77** [comment]
You can see the error in the Receiver setStatus.

https://stackblitz.com/edit/angular-nq4xe9

**Comment by luthor77** [comment]
Thanks for the link, i didn't see this, I think https://ngxs.gitbook.io/ngxs/ could be updated.

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/59209878-fc03ea80-8bb4-11e9-86fa-0f5b5e28ab9c.png)

**Comment by luthor77** [comment]
![stackblitz-error](https://user-images.githubusercontent.com/31356395/59210269-98ad9480-8b83-11e9-97a0-a1f6c0d24a3b.png)

**Comment by luthor77** [comment]
Oh, So I just need to pass the Model?! Ok, only one more question, using the ImmutableSelector should be able to modify the returned object?

**Comment by splincode** [comment]
yes

**Comment by luthor77** [comment]
Ok, sometimes I can't, I will investigate better, if I can't resolve I'll open an issue. Thanks for the help.
