### ISSUE TITLE
Updating Reactive Form in State

### ISSUE THREAD

**Issue by Steven-Harris** [ngxs-labs/immer-adapter#429]
I am having an issue using immer on a Reactive Form in my state. Here is an example of what I am doing.

```
import { State, Action, StateContext } from '@ngxs/store';
import { ImmutableContext } from '@ngxs-labs/immer-adapter';
export class UpdateName {
  public static readonly type = '[Animals] Update Name';
  constructor(public name: string) {}
}

@State<AnimalsStateModel>({
  name: 'animals',
  defaults: {
    zebra:  new FormGroup({
      name: new FormControl('zebra')
    }),
  }
})
export class AnimalState {

  @Action(UpdateName)
  @ImmutableContext()
  public updateName({ getState, setState }: StateContext<AnimalsStateModel>, payload: UpdateName): void {
    setState((state: AnimalsStateModel) => ({
       state.zebra.reset(payload);
       return state;
    }));
  }
}
```

This results in the following error...
```Cannot assign to read only property '_pendingValue' of object '[object Object]'```

Is there something I am doing wrong?

Versions
@angular/* : "^8.0.0"
@ngxs/store: "^3.6.0"
@ngxs-labs/immer-adapter: "^3.0.5"

**Comment by splincode** [comment]
Don’t use FormGroup in state
https://www.ngxs.io/recipes/style-guide#avoid-saving-class-based-instances-in-your-state

**Comment by Steven-Harris** [comment]
ok, thanks
