### ISSUE TITLE
peer dependency on  @ngxs-labs/emitter ?

### ISSUE THREAD

**Issue by xmlking** [ngxs-labs/immer-adapter#45]
when I install `@ngxs-labs/immer-adapter` it says it depends on `@ngxs-labs/emitter`

is it really needed ?  I don't see need for  `@ngxs-labs/emitter`!

```
npm WARN @ngxs-labs/immer-adapter@1.1.1 requires a peer of @ngxs-labs/emitter@^1.6.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by arturovt** [comment]
@xmlking Fixed in @1.1.2
